package cn.gezhi.po;

import java.util.ArrayList;
import java.util.List;

public class PositionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public PositionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPositionIdIsNull() {
            addCriterion("position_id is null");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNotNull() {
            addCriterion("position_id is not null");
            return (Criteria) this;
        }

        public Criteria andPositionIdEqualTo(Integer value) {
            addCriterion("position_id =", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotEqualTo(Integer value) {
            addCriterion("position_id <>", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThan(Integer value) {
            addCriterion("position_id >", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("position_id >=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThan(Integer value) {
            addCriterion("position_id <", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThanOrEqualTo(Integer value) {
            addCriterion("position_id <=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIn(List<Integer> values) {
            addCriterion("position_id in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotIn(List<Integer> values) {
            addCriterion("position_id not in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdBetween(Integer value1, Integer value2) {
            addCriterion("position_id between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("position_id not between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionNameIsNull() {
            addCriterion("position_name is null");
            return (Criteria) this;
        }

        public Criteria andPositionNameIsNotNull() {
            addCriterion("position_name is not null");
            return (Criteria) this;
        }

        public Criteria andPositionNameEqualTo(String value) {
            addCriterion("position_name =", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameNotEqualTo(String value) {
            addCriterion("position_name <>", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameGreaterThan(String value) {
            addCriterion("position_name >", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameGreaterThanOrEqualTo(String value) {
            addCriterion("position_name >=", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameLessThan(String value) {
            addCriterion("position_name <", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameLessThanOrEqualTo(String value) {
            addCriterion("position_name <=", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameLike(String value) {
            addCriterion("position_name like", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameNotLike(String value) {
            addCriterion("position_name not like", value, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameIn(List<String> values) {
            addCriterion("position_name in", values, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameNotIn(List<String> values) {
            addCriterion("position_name not in", values, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameBetween(String value1, String value2) {
            addCriterion("position_name between", value1, value2, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionNameNotBetween(String value1, String value2) {
            addCriterion("position_name not between", value1, value2, "positionName");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionIsNull() {
            addCriterion("position_permission is null");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionIsNotNull() {
            addCriterion("position_permission is not null");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionEqualTo(Boolean value) {
            addCriterion("position_permission =", value, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionNotEqualTo(Boolean value) {
            addCriterion("position_permission <>", value, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionGreaterThan(Boolean value) {
            addCriterion("position_permission >", value, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("position_permission >=", value, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionLessThan(Boolean value) {
            addCriterion("position_permission <", value, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionLessThanOrEqualTo(Boolean value) {
            addCriterion("position_permission <=", value, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionIn(List<Boolean> values) {
            addCriterion("position_permission in", values, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionNotIn(List<Boolean> values) {
            addCriterion("position_permission not in", values, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionBetween(Boolean value1, Boolean value2) {
            addCriterion("position_permission between", value1, value2, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionPermissionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("position_permission not between", value1, value2, "positionPermission");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryIsNull() {
            addCriterion("position_salary is null");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryIsNotNull() {
            addCriterion("position_salary is not null");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryEqualTo(Double value) {
            addCriterion("position_salary =", value, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryNotEqualTo(Double value) {
            addCriterion("position_salary <>", value, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryGreaterThan(Double value) {
            addCriterion("position_salary >", value, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryGreaterThanOrEqualTo(Double value) {
            addCriterion("position_salary >=", value, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryLessThan(Double value) {
            addCriterion("position_salary <", value, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryLessThanOrEqualTo(Double value) {
            addCriterion("position_salary <=", value, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryIn(List<Double> values) {
            addCriterion("position_salary in", values, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryNotIn(List<Double> values) {
            addCriterion("position_salary not in", values, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryBetween(Double value1, Double value2) {
            addCriterion("position_salary between", value1, value2, "positionSalary");
            return (Criteria) this;
        }

        public Criteria andPositionSalaryNotBetween(Double value1, Double value2) {
            addCriterion("position_salary not between", value1, value2, "positionSalary");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 16 11:44:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}