package cn.gezhi.po;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_name
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_permission
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Boolean positionPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_salary
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Double positionSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_id
     *
     * @return the value of position.position_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_id
     *
     * @param positionId the value for position.position_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_name
     *
     * @return the value of position.position_name
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_name
     *
     * @param positionName the value for position.position_name
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_permission
     *
     * @return the value of position.position_permission
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Boolean getPositionPermission() {
        return positionPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_permission
     *
     * @param positionPermission the value for position.position_permission
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setPositionPermission(Boolean positionPermission) {
        this.positionPermission = positionPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_salary
     *
     * @return the value of position.position_salary
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Double getPositionSalary() {
        return positionSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_salary
     *
     * @param positionSalary the value for position.position_salary
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setPositionSalary(Double positionSalary) {
        this.positionSalary = positionSalary;
    }
}