package cn.gezhi.po;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.position_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.users_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.section_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_sex
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private String staffSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_state
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Boolean staffState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_tel
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private String staffTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.position_id
     *
     * @return the value of staff.position_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.position_id
     *
     * @param positionId the value for staff.position_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.users_id
     *
     * @return the value of staff.users_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.users_id
     *
     * @param usersId the value for staff.users_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.section_id
     *
     * @return the value of staff.section_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.section_id
     *
     * @param sectionId the value for staff.section_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_sex
     *
     * @return the value of staff.staff_sex
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getStaffSex() {
        return staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_sex
     *
     * @param staffSex the value for staff.staff_sex
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setStaffSex(String staffSex) {
        this.staffSex = staffSex == null ? null : staffSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_state
     *
     * @return the value of staff.staff_state
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Boolean getStaffState() {
        return staffState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_state
     *
     * @param staffState the value for staff.staff_state
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setStaffState(Boolean staffState) {
        this.staffState = staffState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_tel
     *
     * @return the value of staff.staff_tel
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getStaffTel() {
        return staffTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_tel
     *
     * @param staffTel the value for staff.staff_tel
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setStaffTel(String staffTel) {
        this.staffTel = staffTel == null ? null : staffTel.trim();
    }
}