package cn.gezhi.po;

public class Users {
    /**
     *
     *
     *
     *
     */
    private Integer usersId;

    /**
     *
     *
     *
     *
     */
    private String usersUsername;

    /**
     *
     *
     *
     *
     */
    private String usersPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_state
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    private Boolean usersState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_id
     *
     * @return the value of users.users_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_id
     *
     * @param usersId the value for users.users_id
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_username
     *
     * @return the value of users.users_username
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getUsersUsername() {
        return usersUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_username
     *
     * @param usersUsername the value for users.users_username
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setUsersUsername(String usersUsername) {
        this.usersUsername = usersUsername == null ? null : usersUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_password
     *
     * @return the value of users.users_password
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public String getUsersPassword() {
        return usersPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_password
     *
     * @param usersPassword the value for users.users_password
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword == null ? null : usersPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_state
     *
     * @return the value of users.users_state
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public Boolean getUsersState() {
        return usersState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_state
     *
     * @param usersState the value for users.users_state
     *
     * @mbggenerated Thu Aug 16 11:44:26 CST 2018
     */
    public void setUsersState(Boolean usersState) {
        this.usersState = usersState;
    }
}